name: CI 

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '22'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Build
      env:
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      run: ./gradlew build
